
const Trips = [
  {
    TripID: "100",
    PhotoAlt: "Tokyo Cityscape",
    PhotoSource: "/src/assets/Tokyo.jpg",
    Location: "Japan",
    Dates: "March 1 – March 14",
    Fact:
      "I went to Japan to mix work and wander. I spent days in Tokyo’s startup districts, rode the Shinkansen to Kyoto, and sat in small teahouses watching cherry blossoms drift by. On quiet mornings, I sketched app ideas while sipping green tea, and in the evenings I wandered neon‑lit alleys just to soak it all in.",
    PosterID: "MikeWeaver98",
    Likes: ["JohnDoe", "LukeSkywalker", "IndianaJones", "JackSparrow" , "fakeuser1", "fakeuser4", "fakeuser5", "fakeuser6", "fakeuser7", "fakeuser8", "fakeuser9", "fakeuser10", "fakeuser11"],
  },
  {
    TripID: "101",
    PhotoAlt: "Great Wall of China",
    PhotoSource: "/src/assets/China.jpeg",
    Location: "China",
    Dates: "May 10 – May 25",
    Fact:
      "China was a journey through time. I climbed sections of the Great Wall at dawn, toured the Forbidden City by lantern light, and drifted down the Li River among limestone peaks. Shanghai’s skyline felt futuristic, but its old alleyways grounded me — I found balance in the contrast.",
    PosterID: "MikeWeaver98",
    Likes: ["TedLasso22", "JohnDoe", "WillTravels67" , "fakeuser1", "fakeuser2", "fakeuser3", "fakeuser11"],
  },
  {
    TripID: "102",
    PhotoAlt: "Nepal Mountains",
    PhotoSource: "/src/assets/Nepal.jpg",
    Location: "Nepal",
    Dates: "April 5 – April 20",
    Fact:
      "Trekking in Nepal was humbling. I hiked up rugged mountain trails, stayed in cliffside guesthouses, and shared stories with Sherpa guides by firelight. One night, I lay outside under the stars, breathing in the cold air, and realized how small I really am in the face of those peaks.",
    PosterID: "MikeWeaver98",
    Likes: ["JohnDoe", "NateEisenberg2000", "WillTravels67"],
  },
  {
    TripID: "103",
    PhotoAlt: "Taj Mahal at Sunset",
    PhotoSource: "/src/assets/Taj Mahal.jpg",
    Location: "India",
    Dates: "October 1 – October 14",
    Fact:
      "India was a whirlwind. I wandered through Delhi’s bazaars, tasted street food that challenged everything I thought I knew about spice, and watched the Taj Mahal glow in the sunset. I also made a quiet stop in Kerala’s backwaters, riding a houseboat and listening to the gentle lapping of water at dusk.",
    PosterID: "MikeWeaver98",
    Likes: ["JohnDoe", "LukeSkywalker", "JackSparrow", "IndianaJones" , "fakeuser5", "fakeuser6", "fakeuser7", "fakeuser8",  "fakeuser10", "fakeuser11"],
  },
  {
    TripID: "104",
    PhotoAlt: "Cliffs on Irish Coast",
    PhotoSource: "/src/assets/Ireland.jpg",
    Location: "Ireland",
    Dates: "July 6 – July 14",
    Fact:
      "Ireland felt like a page from a storybook. I drove winding coastal roads, explored castles perched on cliffs, and ducked into pubs to hear live folk music. One rainy afternoon, I parked by a lake, cracked open my laptop, and wrote in my journal, letting the mist and quiet guide my thoughts.",
    PosterID: "MikeWeaver98",
    Likes: ["TedLasso22", "JohnDoe", "WillTravels67", "LukeSkywalker" , "fakeuser1", "fakeuser2", "fakeuser3", "fakeuser4", "fakeuser5", "fakeuser6", "fakeuser7", "fakeuser8", "fakeuser9", "fakeuser10", "fakeuser11"],
  },
  {
    TripID: "105",
    PhotoAlt: "Zambia Savannah",
    PhotoSource: "/src/assets/Zambia.jpg",
    Location: "Zambia",
    Dates: "August 20 – September 1",
    Fact:
      "In Zambia, I went on safari, watched herds of elephants move across golden plains, and camped under a sky I didn’t think could exist. The sound of Victoria Falls in the distance was like a heartbeat, and at night the stars felt endless. I spent time with guides, talking about conservation and how travel shapes us.",
    PosterID: "MikeWeaver98",
    Likes: ["JohnDoe", "TedLasso22", "IndianaJones" , "fakeuser1", "fakeuser2", "fakeuser3",  "fakeuser9", "fakeuser10", "fakeuser11"],
  },
  {
    TripID: "106",
    PhotoAlt: "Malawi Lake Shore",
    PhotoSource: "/src/assets/Malawi.jpg",
    Location: "Malawi",
    Dates: "September 15 – September 25",
    Fact:
      "Malawi was for quiet reflection. I kayaked on Lake Malawi’s crystalline waters, visited lakeside villages, and listened to fishermen sing as the sun set. In the evenings, I sat by firelight and just watched the stars ripple off the water. It was a reset I didn't know I desperately needed.",
    PosterID: "MikeWeaver98",
    Likes: ["WillTravels67", "JohnDoe", "NateEisenberg2000" , "fakeuser1", "fakeuser2", "fakeuser3", "fakeuser6", "fakeuser7", "fakeuser8", "fakeuser9", "fakeuser10", "fakeuser11"],
  },
  {
    TripID: "107",
    PhotoAlt: "Machu Picchu Ruins",
    PhotoSource: "/src/assets/Machu Pichu.jpg",
    Location: "Peru",
    Dates: "November 1 – November 10",
    Fact:
      "I hiked to Machu Picchu on foot, through misty mountain trails and remote villages. When I finally arrived, I watched the sun hit the ancient stones and felt a deep sense of awe — like history was breathing beneath my feet. I also spent time in small Andean towns, talking with locals about their stories and how they carry tradition forward.",
    PosterID: "MikeWeaver98",
    Likes: ["IndianaJones", "JohnDoe", "LukeSkywalker" , "fakeuser1", "fakeuser2", "fakeuser9", "fakeuser10", "fakeuser11"],
  },
  {
    TripID: "108",
    PhotoAlt: "Patagonian Peaks",
    PhotoSource: "/src/assets/Patagonia.jpg",
    Location: "Argentina",
    Dates: "December 5 – December 15",
    Fact:
      "Patagonia was raw: granite peaks, wind-whipped trails, and nights in tiny mountain huts. I spent days hiking, evenings journaling by dim lights, and mornings staring out at glaciers. There’s something about that kind of wilderness that clears your mind — and gives you ideas you never expected.",
    PosterID: "MikeWeaver98",
    Likes: ["JohnDoe", "JackSparrow", "TedLasso22" , "fakeuser1", "fakeuser2", "fakeuser3", "fakeuser4", "fakeuser9", "fakeuser10", "fakeuser11"],
  },
  {
    TripID: "109",
    PhotoAlt: "Andean Lake and Mountains",
    PhotoSource: "/src/assets/Andean Lake.jpg",
    Location: "Chile",
    Dates: "December 20 – December 30",
    Fact:
      "Chile felt like a meditation in landscape: alpine lakes, jagged mountain ridges, and desert valleys that went on forever. I tasted local wine, watched condors soar, and sat on rocky shores just thinking about how to build a sustainable feature in my app inspired by these wild shapes.",
    PosterID: "MikeWeaver98",
    Likes: ["LukeSkywalker", "NateEisenberg2000", "JohnDoe", "WillTravels67" , "fakeuser1", "fakeuser2", "fakeuser6", "fakeuser7", "fakeuser8", "fakeuser9", "fakeuser10", "fakeuser11"],
  },
  {
    TripID: "110",
    PhotoAlt: "Historic Istanbul Skyline",
    PhotoSource: "/src/assets/Istanbul.jpg",
    Location: "Turkey",
    Dates: "April 10 – April 20",
    Fact:
      "Turkey was a bridge between eras: walking through the Grand Bazaar felt like stepping into another time, and beneath mosques I pondered how old ideas resurface in new code. I explored cisterns, sipped strong coffee in hidden courtyards, and sketched features that felt inspired by Byzantine geometry.",
    PosterID: "MikeWeaver98",
    Likes: ["JohnDoe", "JackSparrow", "IndianaJones" , "fakeuser1", "fakeuser2", "fakeuser3", "fakeuser4", "fakeuser5", "fakeuser6", "fakeuser7", "fakeuser8", "fakeuser9", "fakeuser10", "fakeuser11"],
  },
  {
    TripID: "111",
    PhotoAlt: "Bangkok Street Life",
    PhotoSource: "/src/assets/Bangkok.jpg",
    Location: "Thailand",
    Dates: "March 5 – March 15",
    Fact:
      "Thailand was sensory: street food carts, glowing lanterns, golden temples. I rode tuk‑tuks through neon markets, then spent calm mornings by river temples thinking about where my app could go next. It was travel, yes — but also a creative sprint with a backdrop of incense and laughter.",
    PosterID: "MikeWeaver98",
    Likes: ["WillTravels67", "JohnDoe", "TedLasso22", "LukeSkywalker", "fakeuser1", "fakeuser2",  "fakeuser5", "fakeuser6", "fakeuser7", "fakeuser8", "fakeuser9", "fakeuser10", "fakeuser11"],
  },
  {
    TripID: "600",
    PhotoAlt: "Sahara Dunes at Sunset",
    PhotoSource: "/src/assets/Sahara.jpg",
    Location: "Sahara Desert",
    Dates: "May 2 – May 10",
    Fact:
      "I decided to seed a trip across the Sahara — rented a rugged 4x4, drove between dunes, and slept under a sky so full of stars I thought it might collapse. Some nights I pulled out my laptop by lantern light and sketched out app ideas, wondering if inspiration is always louder in quiet places.",
    PosterID: "JohnDoe",
    Likes: ["MikeWeaver98", "LukeSkywalker", "TedLasso22", "fakeuser1", "fakeuser2",  "fakeuser7", "fakeuser8", "fakeuser9", "fakeuser10", "fakeuser11"],
  },
  {
    TripID: "601",
    PhotoAlt: "Rainforest Canopy",
    PhotoSource: "/src/assets/Rainforest.jpg",
    Location: "Costa Rica",
    Dates: "August 15 – August 22",
    Fact:
      "For a more contemplative trip, I “went” to Costa Rica in my mock data. I hiked cloud forests, kayaked rivers, and stayed in a treehouse that felt like a floating office. The green was overwhelming in a good way, and I spent afternoons writing pseudocode inspired by twisting vines and misty heights.",
    PosterID: "JohnDoe",
    Likes: ["WillTravels67", "MikeWeaver98", "JackSparrow", "NateEisenberg2000" , "fakeuser1", "fakeuser2", "fakeuser3", "fakeuser4", "fakeuser5", "fakeuser6", "fakeuser7", "fakeuser8", "fakeuser9", "fakeuser10", "fakeuser11"],
  },
  {
    TripID: "300",
    PhotoAlt: "Tatooine Dune Ridge",
    PhotoSource: "/src/assets/Tatooine.jpg",
    Location: "Tatooine",
    Dates: "August 10 – August 18",
    Fact:
      "I returned to Tatooine to walk the dunes I once called home. The twin suns beat down, but in the evening I felt the Force hum stronger. I spent time thinking about legacy — where I came from, where I’m going — and how even in the vast desert there’s room for growth.",
    PosterID: "LukeSkywalker",
    Likes: ["JohnDoe", "IndianaJones", "MikeWeaver98" , "fakeuser1", "fakeuser2", "fakeuser3", "fakeuser4", "fakeuser5", "fakeuser6", "fakeuser7", "fakeuser8", "fakeuser9", "fakeuser10", "fakeuser11"],
  },
  {
    TripID: "301",
    PhotoAlt: "Dagobah Swamp Mist",
    PhotoSource: "/src/assets/Dagobah.jpg",
    Location: "Dagobah",
    Dates: "September 5 – September 11",
    Fact:
      "Dagobah was a test of stillness. I trained in the swamp, meditated under gnarled trees, and leaned into the swamp’s oppressive silence. It challenged me mentally: to trust the Force, to trust myself, and to find calm in chaos.",
    PosterID: "LukeSkywalker",
    Likes: ["IndianaJones", "JackSparrow" , "fakeuser1", "fakeuser2", "fakeuser3", "fakeuser4", "fakeuser5", "fakeuser6", "fakeuser7", "fakeuser8", "fakeuser9", "fakeuser10", "fakeuser11"],
  },
  {
    TripID: "302",
    PhotoAlt: "Ahch‑To Island Cliffs",
    PhotoSource: "/src/assets/Ahch-to.jpg",
    Location: "Ahch‑To",
    Dates: "October 12 – October 18",
    Fact:
      "On Ahch‑To, I walked ancient Jedi ruins and cliffside paths overlooking the sea. The wind was salty, the stones were old, and I felt a deep sense of purpose. It was part pilgrimage, part research — a chance to reconnect with who I am and what I’ve become.",
    PosterID: "LukeSkywalker",
    Likes: ["JohnDoe", "MikeWeaver98" , "fakeuser1", "fakeuser2", "fakeuser3", "fakeuser7", "fakeuser8", "fakeuser9", "fakeuser10", "fakeuser11"],
  },
  {
    TripID: "400",
    PhotoAlt: "Caribbean Hidden Cove",
    PhotoSource: "/src/assets/Caribbean.jpg",
    Location: "Caribbean Sea",
    Dates: "June 5 – June 20",
    Fact:
      "I sailed the Caribbean in search of treasure and freedom. Hidden coves, reefs, and palm‑fringed islands became my playground. The sea didn’t care about my past or my future — it just cared about my next adventure, and that’s exactly how I like it.",
    PosterID: "JackSparrow",
    Likes: ["JohnDoe", "LukeSkywalker", "MikeWeaver98", "IndianaJones", "TedLasso22" , "fakeuser1", "fakeuser2", "fakeuser3", "fakeuser4", "fakeuser5", "fakeuser6", "fakeuser7", "fakeuser8", "fakeuser9", "fakeuser10", "fakeuser11"],
  },
  {
    TripID: "401",
    PhotoAlt: "Storm at Sea",
    PhotoSource: "/src/assets/Storm.jpg",
    Location: "Open Ocean",
    Dates: "July 1 – July 6",
    Fact:
      "A storm found me at sea. Lightning cracked, waves towered, and for a moment the ship felt like it might tear apart. But I laughed — because chaos is part of the deal when you’re a pirate. It’s not always safe, but it’s always alive.",
    PosterID: "JackSparrow",
    Likes: ["IndianaJones", "LukeSkywalker" , "fakeuser1", "fakeuser2", "fakeuser3", "fakeuser6", "fakeuser7", "fakeuser8", "fakeuser9", "fakeuser10", "fakeuser11"],
  },
  {
    TripID: "500",
    PhotoAlt: "Andean Ruin Entrance",
    PhotoSource: "/src/assets/Ruins.jpg",
    Location: "Andes Mountains, Peru",
    Dates: "September 1 – September 12",
    Fact:
      "I trekked into the Andes, following old maps and faint legends, until I uncovered the entrance to a forgotten temple. Vines curled around ancient stone, and carvings whispered stories of civilizations lost. There’s something electric about dust and history — like you’re touching time itself.",
    PosterID: "IndianaJones",
    Likes: ["MikeWeaver98", "JohnDoe", "LukeSkywalker", "fakeuser1", "fakeuser2", "fakeuser3", "fakeuser4", "fakeuser5", "fakeuser6", "fakeuser7", "fakeuser8", "fakeuser9", "fakeuser10", "fakeuser11"],
  },
  {
    TripID: "501",
    PhotoAlt: "Temple Underground Chamber",
    PhotoSource: "/src/assets/Temple.jpg",
    Location: "Hidden Cavern",
    Dates: "September 7 – September 10",
    Fact:
      "Inside a secret cavern beneath the ruins, I found relics tucked into shadows and manuscripts that seemed to hum with memory. The air was damp, the stone was cool, and every step echoed. It felt like I was not just exploring history — but carrying it forward.",
    PosterID: "IndianaJones",
    Likes: ["JohnDoe", "JackSparrow", "fakeuser1", "fakeuser2", "fakeuser3", "fakeuser4", "fakeuser5", "fakeuser6", "fakeuser7", "fakeuser8", "fakeuser9", "fakeuser10", "fakeuser11"],
  },
  {
    TripID: "200",
    PhotoAlt: "Northern Lights over Norway",
    PhotoSource: "/src/assets/Northern Lights.jpg",
    Location: "Norway",
    Dates: "February 1 – February 10",
    Fact:
      "I went to Norway to chase the northern lights and pause my coding brain. I stayed in remote cabins, watched the aurora paint the sky, and realized some ideas don’t come from loops — they come from silence. It was a trip that felt like a reboot, in every sense.",
    PosterID: "TedLasso22",
    Likes: ["JohnDoe", "MikeWeaver98", "IndianaJones", "JackSparrow" , "fakeuser1", "fakeuser2", "fakeuser3", "fakeuser4", "fakeuser5", "fakeuser6", "fakeuser7", "fakeuser8", "fakeuser9", "fakeuser10", "fakeuser11"],
  },
  {
    TripID: "201",
    PhotoAlt: "Vietnam Jungle River",
    PhotoSource: "/src/assets/Vietnam.jpg",
    Location: "Vietnam",
    Dates: "June 10 – June 22",
    Fact:
      "Vietnam was lush and alive. I trekked rice terraces, paddled rivers, and explored jungle pagodas. I’d stop mid‑hike to sketch UI ideas in my notebook, thinking about how growth in nature often mirrors growth in code: layered, incremental, and full of surprises.",
    PosterID: "TedLasso22",
    Likes: ["WillTravels67", "JohnDoe", "LukeSkywalker" , "fakeuser1",  "fakeuser5", "fakeuser6", "fakeuser7", "fakeuser8", "fakeuser9", "fakeuser10", "fakeuser11"],
  },
  {
    TripID: "202",
    PhotoAlt: "Patagonian Glaciers",
    PhotoSource: "/src/assets/Glacier.jpg",
    Location: "Patagonia, Chile",
    Dates: "November 1 – November 14",
    Fact:
      "Patagonia was an edge‑case trip. Glaciers, wind, and icy lakes tested every assumption I had about comfort. I kayaked on cold water, camped under a gallery of stars, and realized that building something meaningful sometimes requires stepping out of your comfort zone — even if it’s freezing.",
    PosterID: "TedLasso22",
    Likes: ["JohnDoe", "WillTravels67", "NateEisenberg2000" , "fakeuser6", "fakeuser7", "fakeuser8", "fakeuser9", "fakeuser10", "fakeuser11"],
  },
  {
    TripID: "700",
    PhotoAlt: "English Lake District",
    PhotoSource: "/src/assets/English Lake.jpg",
    Location: "England (Lake District)",
    Dates: "April 10 – April 17",
    Fact:
      "I took a “mock‑trip” through England’s Lake District — hills, quiet lakes, and cozy pubs all the way. Imagining myself coding in a little cottage with a view, I planned some side‑project features and thought about how calm landscapes make ideas sharper.",
    PosterID: "WillTravels67",
    Likes: ["JohnDoe", "MikeWeaver98", "NateEisenberg2000", "LukeSkywalker" , "fakeuser1", "fakeuser2", "fakeuser3", "fakeuser4", "fakeuser5", "fakeuser6", "fakeuser7", "fakeuser8", "fakeuser9", "fakeuser10", "fakeuser11"],
  },
  {
    TripID: "701",
    PhotoAlt: "Amsterdam Canals at Night",
    PhotoSource: "/src/assets/Amsterdam.jpg",
    Location: "Amsterdam",
    Dates: "September 5 – September 12",
    Fact:
      "In Amsterdam, I imagined myself drifting down canals under orange streetlights, thinking about app UX and flow. I visited cafés, sketched wireframes on napkins, and let the city’s calm energy fuel some of my best ideas yet. Traveling doesn’t always have to be loud to be inspiring.",
    PosterID: "WillTravels67",
    Likes: ["TedLasso22", "JohnDoe" , "fakeuser1", "fakeuser2", "fakeuser3", "fakeuser11"],
  },
];


const Experiences = [
  {
    TripID: "100",
    ExperienceID: "100-1",
    PhotoAlt: "Kyoto Temple Garden",
    PhotoSource: "/src/assets/Kyoto.jpg",
    Date: "March 4, 2025",
    Place: "Kyoto Temple",
    Title: "Zen Garden Reflection",
    Description:
      "I wandered into a quiet temple garden in Kyoto early in the morning. The stone paths were damp, and the air was cool. Sitting on a bench, I closed my eyes and listened — birds, wind, distant prayer chant. It felt like the code in my brain finally paused.",
    PosterID: "MikeWeaver98",
  },
  {
    TripID: "100",
    ExperienceID: "100-2",
    PhotoAlt: "Shinkansen Window View",
    PhotoSource: "/src/assets/Shinkansen.jpg",
    Date: "March 6, 2025",
    Place: "Shinkansen Train",
    Title: "Bullet Train Day",
    Description:
      "Rode the Shinkansen between Kyoto and Tokyo. The landscape blurred outside the window — hills, rice paddies, neon buildings. I used that time to sketch out a feature for the app: something inspired by motion, speed, and transitions.",
    PosterID: "MikeWeaver98",
  },
  {
    TripID: "100",
    ExperienceID: "100-3",
    PhotoAlt: "Mount Fuji at Dusk",
    PhotoSource: "/src/assets/Fuji Night.jpg",
    Date: "March 9, 2025",
    Place: "Fuji Foothills",
    Title: "Fuji at Sunset",
    Description:
      "Climbed to a lookout point near Mount Fuji just before sunset. The sky turned pink and purple, and I felt a weird mix of awe and calm. I pulled out my journal (yes, real code-journal) and jotted down ideas about resilience — how projects are like mountains.",
    PosterID: "MikeWeaver98",
  },
  {
    TripID: "100",
    ExperienceID: "100-4",
    PhotoAlt: "Tokyo Night Walk",
    PhotoSource: "/src/assets/Tokyo Night.jpg",
    Date: "March 11, 2025",
    Place: "Shibuya Crossing",
    Title: "Neon Crosswalk",
    Description:
      "Walked across Shibuya Crossing at night. Lights flashing, people moving in waves, the hum of the city everywhere. I thought about how code can feel like that too — chaotic, alive, and somehow orchestrated.",
    PosterID: "MikeWeaver98",
  },
  {
    TripID: "101",
    ExperienceID: "101-1",
    PhotoAlt: "Great Wall Ridge",
    PhotoSource: "/src/assets/GW Ridge.jpg",
    Date: "May 11, 2025",
    Place: "Great Wall",
    Title: "Sunrise on the Wall",
    Description:
      "Hiked a remote section of the Great Wall with only a handful of others. The sun rose over the mountains and the stones glowed. I paused, leaning on the wall, thinking: legacy matters, whether in architecture or code.",
    PosterID: "MikeWeaver98",
  },
  {
    TripID: "101",
    ExperienceID: "101-2",
    PhotoAlt: "Beijing Alley Market",
    PhotoSource: "/src/assets/Beijing.jpg",
    Date: "May 14, 2025",
    Place: "Beijing Hutong",
    Title: "Alleyway Stroll",
    Description:
      "Took a walk through Beijing’s hutongs (narrow alleys). Locals were out playing chess, families sat outside small shops, lanterns swayed. I bought a snack from a street vendor, and the experience grounded me — reminded me that even high-growth cities have quiet corners.",
    PosterID: "MikeWeaver98",
  },
  {
    TripID: "101",
    ExperienceID: "101-3",
    PhotoAlt: "Li River Boat",
    PhotoSource: "/src/assets/Li RB.jpg",
    Date: "May 18, 2025",
    Place: "Li River",
    Title: "Karst Cruise",
    Description:
      "Took a slow boat down the Li River. Limestone karsts rose from the water like green giants; fishermen cast nets. I leaned on the railing, closed my eyes, and let the water’s rhythm help me think through some complicated UX flow I’d been stuck on.",
    PosterID: "MikeWeaver98",
  },
  {
    TripID: "102",
    ExperienceID: "102-1",
    PhotoAlt: "Himalayan Teahouse",
    PhotoSource: "/src/assets/H TH.jpg",
    Date: "April 8, 2025",
    Place: "Mountain Teahouse",
    Title: "Cliff‑Side Teahouse",
    Description:
      "Stopped at a teahouse perched on a cliff, over a valley so deep I couldn’t see the bottom. The air was thin, tea was warm, conversation soft. I opened my laptop and typed a few lines — mostly personal reflections. It felt like blending remote work and travel in the purest way.",
    PosterID: "MikeWeaver98",
  },
  {
    TripID: "102",
    ExperienceID: "102-2",
    PhotoAlt: "Mountain Stars",
    PhotoSource: "/src/assets/H Stars.jpg",
    Date: "April 12, 2025",
    Place: "Camp Under Stars",
    Title: "Starry Himalayan Night",
    Description:
      "Camped under the Himalayas. At night, the sky was so clear I could see constellations I didn’t even know existed. I lay on my back for hours, thinking about scale — of the universe, of ambition, of how small but important we are in the grand scheme.",
    PosterID: "MikeWeaver98",
  },
  {
    TripID: "103",
    ExperienceID: "103-1",
    PhotoAlt: "Taj Mahal Marble Walk",
    PhotoSource: "/src/assets/Marble.jpg",
    Date: "October 3, 2025",
    Place: "Taj Mahal",
    Title: "Marble Meditation",
    Description:
      "Went to the Taj Mahal in late afternoon. The marble glowed softly, and I walked slowly, letting my thoughts settle. I sketched in my journal: geometry, symmetry, love — and how apps sometimes need that kind of balance too.",
    PosterID: "MikeWeaver98",
  },
  {
    TripID: "103",
    ExperienceID: "103-2",
    PhotoAlt: "Delhi Bazaar",
    PhotoSource: "/src/assets/Bazaar.jpg",
    Date: "October 5, 2025",
    Place: "Old Delhi Market",
    Title: "Spice Market Hustle",
    Description:
      "Roamed through an old Delhi bazaar. Spices stacked in pyramids, voices calling out, rickshaws weaving by. I bought a small bundle of cardamom and tried bargaining — not great at it, but fun. The chaos made me think: good design handles complexity, but also breaths.",
    PosterID: "MikeWeaver98",
  },
  {
    TripID: "103",
    ExperienceID: "103-3",
    PhotoAlt: "Kerala Backwater",
    PhotoSource: "/src/assets/Kerala.jpg",
    Date: "October 9, 2025",
    Place: "Kerala Backwaters",
    Title: "Houseboat Coding",
    Description:
      "Spent a morning on a houseboat in Kerala sailing through backwaters. I opened my laptop and wrote some pseudocode while water lilies floated by. The slow pace and gentle motion gave me space to think differently about my architecture.",
    PosterID: "MikeWeaver98",
  },
  {
    TripID: "103",
    ExperienceID: "103-4",
    PhotoAlt: "Holi Festival Colors",
    PhotoSource: "/src/assets/Holi.jpg",
    Date: "October 11, 2025",
    Place: "Small Town Holi Festival",
    Title: "Color & Chaos",
    Description:
      "I stumbled into a small Holi celebration in a village. People threw colored powder, laughed, danced — everyone was in motion. My shirt ended up neon pink. I realized that sometimes ideas need that kind of chaos: messy but joyful.",
    PosterID: "MikeWeaver98",
  },
  {
    TripID: "104",
    ExperienceID: "104-1",
    PhotoAlt: "Cliffside View",
    PhotoSource: "/src/assets/Cliff.jpg",
    Date: "July 8, 2025",
    Place: "Coastal Cliff Path",
    Title: "Point-to-Point Walk",
    Description:
      "Walked a cliff-side path overlooking crashing waves. Seagulls cried, wind cut across me, and the view was wild but steadied me. I found a rock to sit on, opened my journal, and wrote about how travel reminds you what staying still really means.",
    PosterID: "MikeWeaver98",
  },
  {
    TripID: "106",
    ExperienceID: "106-1",
    PhotoAlt: "Lake Malawi Fisherman",
    PhotoSource: "/src/assets/Fisherman.jpg",
    Date: "September 17, 2025",
    Place: "Lakeshore Village",
    Title: "Fisherman’s Song",
    Description:
      "I visited a lakeshore village in Malawi and watched fishermen pull in nets at dawn. Their voices echoed softly across the water, and they invited me to share breakfast. We talked about the lake, life, and what it means to make a living on water.",
    PosterID: "MikeWeaver98",
  },
  {
    TripID: "106",
    ExperienceID: "106-2",
    PhotoAlt: "Star Reflection on Lake",
    PhotoSource: "/src/assets/S Lake.jpg",
    Date: "September 20, 2025",
    Place: "Lake at Night",
    Title: "Reflections & Stars",
    Description:
      "At night, I kayaked out just enough to feel alone on the lake. The water was mirror-smooth, reflecting stars like glitter. I paused my paddle, closed my eyes, and just floated — it was one of those travel moments that feels like a quiet reset.",
    PosterID: "MikeWeaver98",
  },
  {
    TripID: "107",
    ExperienceID: "107-1",
    PhotoAlt: "Inca Trail Ruins",
    PhotoSource: "/src/assets/Trail.jpg",
    Date: "November 2, 2025",
    Place: "Inca Trail",
    Title: "Trail to Machu Picchu",
    Description:
      "Hiked the ancient Inca Trail at dawn, with cloud‑covered peaks around me. The trail was steep, but every step felt like walking through time. I thought about legacy, structure, and how every project I build is a path — with setbacks, views, and unexpected climbs.",
    PosterID: "MikeWeaver98",
  },
  {
    TripID: "107",
    ExperienceID: "107-2",
    PhotoAlt: "Sunrise Over Ruins",
    PhotoSource: "/src/assets/MP Sunrise.jpg",
    Date: "November 4, 2025",
    Place: "Machu Picchu",
    Title: "Sunrise Citadel",
    Description:
      "Arrived at Machu Picchu just before sunrise. The stones glowed in golden light, mist curled around terraces, and silence ruled. It felt like being at the center of a story — and I promised myself I’d come back with more than a backpack, maybe with something I built.",
    PosterID: "MikeWeaver98",
  },
  {
    TripID: "107",
    ExperienceID: "107-3",
    PhotoAlt: "Mountain Village",
    PhotoSource: "/src/assets/MV.jpg",
    Date: "November 7, 2025",
    Place: "Andean Village",
    Title: "Village Walk",
    Description:
      "Walked into a small Andean village tucked in the hills. Chickens clucked, children ran around, and elders sat outside their homes. I shared a cup of coca tea with a local and listened to their stories — travel isn’t just about monuments, it’s about people.",
    PosterID: "MikeWeaver98",
  },
  {
    TripID: "109",
    ExperienceID: "109-1",
    PhotoAlt: "Andean Lake Sunset",
    PhotoSource: "/src/assets/A Lake S.jpg",
    Date: "December 22, 2025",
    Place: "Andean Lake",
    Title: "Lake at Dusk",
    Description:
      "Sat by a high-altitude lake at dusk. The water changed colors from blue to violet as the sun set behind the mountains. I closed my notebook and just watched — sometimes that’s all travel really is: presence.",
    PosterID: "MikeWeaver98",
  },
  {
    TripID: "110",
    ExperienceID: "110-1",
    PhotoAlt: "Grand Bazaar Alley",
    PhotoSource: "/src/assets/G Bazaar.jpg",
    Date: "April 12, 2025",
    Place: "Grand Bazaar",
    Title: "Bazaar Labyrinth",
    Description:
      "Lost myself in the Grand Bazaar’s winding alleys. The smell of spices, the clink of metalwork, and the hum of bargaining made me feel alive. I bought a small copper lamp and bargained, half as a coder, half as a traveler.",
    PosterID: "MikeWeaver98",
  },
  {
    TripID: "110",
    ExperienceID: "110-2",
    PhotoAlt: "Istanbul Rooftop View",
    PhotoSource: "/src/assets/I Rooftop.jpg",
    Date: "April 15, 2025",
    Place: "Rooftop Terrace",
    Title: "Call to Prayer",
    Description:
      "Watched the sunset from a rooftop terrace. The city’s minarets framed the sky, and the call to prayer echoed softly. I sipped tea, thought about continuity, and how important history is — whether in code or in architecture.",
    PosterID: "MikeWeaver98",
  },
  {
    TripID: "600",
    ExperienceID: "600-1",
    PhotoAlt: "Desert Dune Sunrise",
    PhotoSource: "/src/assets/Dune.jpg",
    Date: "May 3, 2025",
    Place: "Sahara Dunes",
    Title: "Sunrise Over Sand",
    Description:
      "Climbed a dune before dawn. The sand was cool underfoot and the sky slowly lit up in gradients of orange and pink. I sat there, watching shadows stretch, feeling like the world was bigger than any of my day‑to‑day code tasks.",
    PosterID: "JohnDoe",
  },
  {
    TripID: "600",
    ExperienceID: "600-2",
    PhotoAlt: "Night Camp Fire",
    PhotoSource: "/src/assets/Fire.jpg",
    Date: "May 5, 2025",
    Place: "Desert Camp",
    Title: "Campfire Talk",
    Description:
      "At night, I joined other travelers around a campfire. We shared stories — some about home, some about why we travel. I sketched out a new app feature idea inspired by the way firelight dances and how ideas spark in conversation.",
    PosterID: "JohnDoe",
  },
  {
    TripID: "601",
    ExperienceID: "601-1",
    PhotoAlt: "Forest Canopy Bridge",
    PhotoSource: "/src/assets/Forest CB.jpg",
    Date: "August 16, 2025",
    Place: "Cloud Forest Canopy",
    Title: "Canopy Walk",
    Description:
      "Walked on a suspension bridge high in the trees. Mist rolled in, birds called, leaves dripped with dew. I felt suspended in time, like a piece of data floating in memory — peaceful, connected, alive.",
    PosterID: "JohnDoe",
  },
  {
    TripID: "300",
    ExperienceID: "300-1",
    PhotoAlt: "Dune Shadows Tatooine",
    PhotoSource: "/src/assets/DST.jpg",
    Date: "August 11, 2025",
    Place: "Tatooine Dunes",
    Title: "Morning Dunes",
    Description:
      "I walked the dunes at sunrise. The twin suns weren’t up yet, and the sand whispered under my boots. I closed my eyes and felt the Force in every grain, grateful for the quiet and the memory of home.",
    PosterID: "LukeSkywalker",
  },
  {
    TripID: "301",
    ExperienceID: "301-1",
    PhotoAlt: "Dagobah Foggy Trees",
    PhotoSource: "/src/assets/DFT.jpg",
    Date: "September 6, 2025",
    Place: "Dagobah Swamp",
    Title: "Swamp Meditation",
    Description:
      "The swamp was saturated in mist. Trees dripped, the ground squelched beneath me, and I felt the Force more strongly in the quiet than ever. I sat with my lightsaber off, breathing, listening — learning again.",
    PosterID: "LukeSkywalker",
  },
  {
    TripID: "302",
    ExperienceID: "302-1",
    PhotoAlt: "Cliff Ruins Ahch‑To",
    PhotoSource: "/src/assets/CRA.jpg",
    Date: "October 14, 2025",
    Place: "Ahch‑To Cliff",
    Title: "Ruins on the Cliffs",
    Description:
      "Climbed the rocky steps to ancient Jedi ruins. The wind was strong, salt in the air, and the stones were carved with symbols I couldn’t decipher — but I felt their weight. I closed my eyes and thought about legacy and what I must pass on.",
    PosterID: "LukeSkywalker",
  },
  {
    TripID: "400",
    ExperienceID: "400-1",
    PhotoAlt: "Palm Cove Water",
    PhotoSource: "/src/assets/PCW.jpg",
    Date: "June 8, 2025",
    Place: "Secluded Cove",
    Title: "Anchor by Palm Trees",
    Description:
      "Dropped anchor at a hidden cove shaded by palms. The sea was calm, salt‑sweet breeze, and for a moment it felt like I owned the horizon. I cracked open a bottle, leaned back, and let the waves sing me a pirate lullaby.",
    PosterID: "JackSparrow",
  },
  {
    TripID: "401",
    ExperienceID: "401-1",
    PhotoAlt: "Ship in Storm",
    PhotoSource: "/src/assets/BP.jpg",
    Date: "July 3, 2025",
    Place: "Rolling Ocean",
    Title: "Tempest Ride",
    Description:
      "The waves slammed, the ship groaned, and lightning lit up the sky. I gripped the helm, water crashing over the deck. But I laughed — because what’s a pirate without a little chaos? It tasted like salt and freedom.",
    PosterID: "JackSparrow",
  },
  {
    TripID: "500",
    ExperienceID: "500-1",
    PhotoAlt: "Andean Temple Wall",
    PhotoSource: "/src/assets/IJ.jpg",
    Date: "September 3, 2025",
    Place: "Ancient Temple",
    Title: "Carved Secrets",
    Description:
      "I traced my fingers over ancient carved reliefs in a temple deep in the Andes. Vines curled around stone, and each symbol felt like a clue — not just about the past, but about what we leave behind. My archaeologist heart was racing.",
    PosterID: "IndianaJones",
  },
  {
    TripID: "500",
    ExperienceID: "500-2",
    PhotoAlt: "Andean Summit View",
    PhotoSource: "/src/assets/SV.jpg",
    Date: "September 6, 2025",
    Place: "Mountain Summit",
    Title: "Summit Discovery",
    Description:
      "Reached a high viewpoint overlooking the Andes ruins. Clouds floated below; wind whipped my hat; I realized how small I am against time and rock. It’s moments like this that make history feel alive.",
    PosterID: "IndianaJones",
  },
  {
    TripID: "200",
    ExperienceID: "200-1",
    PhotoAlt: "Aurora Sky",
    PhotoSource: "/src/assets/AS.jpg",
    Date: "February 3, 2025",
    Place: "Northern Wilderness",
    Title: "Dancing Lights",
    Description:
      "Stood outside a small cabin at night, watching the aurora borealis swirl. The sky was alive, cold air biting my cheeks. I typed notes on my phone — not code, just reflections. The lights whispered about distance, possibility, and new direction.",
    PosterID: "TedLasso22",
  },
  {
    TripID: "201",
    ExperienceID: "201-1",
    PhotoAlt: "Vietnam Rice Terrace",
    PhotoSource: "/src/assets/Vietnam Rice Terrace.jpg",
    Date: "June 13, 2025",
    Place: "Sapa Terraces",
    Title: "Terrace Trek",
    Description:
      "Hiked the rice terraces in northern Vietnam. Terraced fields glowed green, water buffalo grazed, and farmers waved as I passed. I paused halfway up and just watched — such a simple, grounded moment, I almost forgot I was building a data model back home.",
    PosterID: "TedLasso22",
  },
  {
    TripID: "201",
    ExperienceID: "201-2",
    PhotoAlt: "Hill Pagoda",
    PhotoSource: "/src/assets/Hill Pagoda.jpg",
    Date: "June 15, 2025",
    Place: "Hilltop Pagoda",
    Title: "Pagoda Sunrise",
    Description:
      "I climbed to a pagoda at dawn. Mist curled around the stairs, the world quiet except for prayer bells in the distance. I breathed in deep, thinking about what it means to climb — in life, in code, and in memory.",
    PosterID: "TedLasso22",
  },
  {
    TripID: "700",
    ExperienceID: "700-1",
    PhotoAlt: "Lake District Water",
    PhotoSource: "/src/assets/Lake District Water.jpg",
    Date: "April 12, 2025",
    Place: "Lake District Lake",
    Title: "Lakeside Sketch",
    Description:
      "Sat by a lake in the English hills, sketching the outline of hills and reflections. The air was cool, the wind soft, and I felt calm enough to imagine new app UI ideas. Sometimes travel is just an excuse to storyboard in real life.",
    PosterID: "WillTravels67",
  },
  {
    TripID: "700",
    ExperienceID: "700-2",
    PhotoAlt: "Village Pub Night",
    PhotoSource: "/src/assets/Pub.jpg",
    Date: "April 14, 2025",
    Place: "Cozy Village Pub",
    Title: "Pub Brainstorm",
    Description:
      "Spent an evening in a small village pub. Cider, wooden tables, locals telling stories. I pulled out a notebook and sketched a growth plan for my side‑project. The hum of conversation felt like fuel.",
    PosterID: "WillTravels67",
  },
  {
    TripID: "701",
    ExperienceID: "701-1",
    PhotoAlt: "Amsterdam Canal by Night",
    PhotoSource: "/src/assets/Amsterdam Canal by Night.jpg",
    Date: "September 8, 2025",
    Place: "Amsterdam Canal",
    Title: "Canal Cruise at Dusk",
    Description:
      "Took a slow canal boat ride in Amsterdam just as dusk fell. Streetlamps reflected in the water, bicycles hummed across bridges, and the world felt calm and full. I closed my notebook, leaned back, and let the city’s rhythm inspire me.",
    PosterID: "WillTravels67",
  },
];


const Accounts = {
  JohnDoe: {
    Bio: {
      Name: "John Doe",
      DOB: "01/01/1985",
      AboutMe:
        "I build my travel stories like I build code — thoughtfully, one module at a time. When I'm not daydreaming about dunes or forests, I’m sketching app ideas on napkins and laptops. Travel is my narrative, and code is my medium.",
      PinnedTrip: "Sahara Desert",
      UpcomingTrip: "Costa Rica Cloud Forest",
      PhotoSource: "/src/assets/John Doe.jpg",
      UserID: "JohnDoe",
      Following: ["LukeSkywalker", "MikeWeaver98"],
    },
  },
  JackSparrow: {
    Bio: {
      Name: "Captain Jack Sparrow",
      DOB: "Unknown",
      AboutMe:
        "I sail because the sea is the only bug-free environment I’ve found. Treasure? Maybe. Adventure? Definitely. I’m less about gold and more about how wild the horizon can be.",
      PinnedTrip: "Caribbean Sea",
      UpcomingTrip: "Stormy Horizon",
      PhotoSource: "/src/assets/Sparrow.jpeg",
      UserID: "JackSparrow",
      Following: ["JohnDoe", "LukeSkywalker"],
    },
  },
  LukeSkywalker: {
    Bio: {
      Name: "Luke Skywalker",
      DOB: "19 BBY",
      AboutMe:
        "The Force is part of me — but so is curiosity. I travel to test my balance, learn patience, and listen more carefully. Whether it’s remote islands or quiet temples, every “out there” has something to teach.",
      PinnedTrip: "Tatooine",
      UpcomingTrip: "Ahch-To Return",
      PhotoSource: "/src/assets/Luke.jpeg",
      UserID: "LukeSkywalker",
      Following: ["JohnDoe"],
    },
  },
  IndianaJones: {
    Bio: {
      Name: "Dr. Indiana Jones",
      DOB: "12/01/1899",
      AboutMe:
        "Archaeologist by trade, adventurer by heart. I dig into history so others don’t forget it. I’m happiest when I’m dusty, sweaty, and peeling vines off ancient stone — because that’s where stories hide.",
      PinnedTrip: "Andes Ruins",
      UpcomingTrip: "Amazon Expedition",
      PhotoSource: "/src/assets/Indy.jpeg",
      UserID: "IndianaJones",
      Following: ["LukeSkywalker"],
    },
  },
  MikeWeaver98: {
    Bio: {
      Name: "Mike Weaver",
      DOB: "01/03/1998",
      AboutMe:
        "Built this platform so I could share travel + code + connection. Every trip I take is a little feature in my life’s app; every story is a commit. I'm as passionate about APIs as I am about sunsets.",
      PinnedTrip: "Japan",
      UpcomingTrip: "Peru",
      PhotoSource: "/src/assets/Mike.jpg",
      UserID: "MikeWeaver98",
      Following: ["WillTravels67", "TedLasso22"],
    },
  },
  TedLasso22: {
    Bio: {
      Name: "Ted Lasso",
      DOB: "04/03/1998",
      AboutMe:
        "I am the coach of a football team and just getting into travel! Check out my trips around Europe!",
      PinnedTrip: "Norway",
      UpcomingTrip: "Vietnam",
      PhotoSource: "/src/assets/Ted Lasso.jpg",
      UserID: "TedLasso22",
      Following: ["MikeWeaver98", "NateEisenberg2000"],
    },
  },
  WillTravels67: {
    Bio: {
      Name: "Will Weaver",
      DOB: "01/03/1998",
      AboutMe:
        "Curiosity + creativity is my travel formula. I’m always sketching side-project ideas in cafés, chasing inspiration in back alleys, and treating maps like storyboards. Travel doesn’t just fuel me — it designs me.",
      PinnedTrip: "England (Lake District)",
      UpcomingTrip: "Amsterdam Canal Ride",
      PhotoSource: "/src/assets/Will.jpg",
      UserID: "WillTravels67",
      Following: ["NateEisenberg2000", "JohnDoe"],
    },
  },
};

const UserID = "MikeWeaver98";

export { Trips, Experiences, Accounts, UserID };
